# Generated by Django 6.0 on 2025-12-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='topic',
            field=models.CharField(default='General Class', max_length=200),
        ),
    ]
