# Generated by Django 6.0 on 2025-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendancesession_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='security_references/'),
        ),
    ]
