# Generated by Django 6.0 on 2025-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_captures/'),
        ),
    ]
